[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/mypy_stubs"

# Demos are currently outdated and cause lots of errors.  Exclude them until the issues
# are fixed.
exclude = "demos/"

[[tool.mypy.overrides]]
module = [
    "context",
    "lightargs",
    "matplotlib.*",
    "o80",
    "o80_pam",
    "pam_configuration",
    "pam_interface",
    "pam_models",
    "pam_mujoco_wrp",
    "shared_memory",
    "signal_handler",
]
ignore_missing_imports = true
